"""Generate docs/kernel-coverage.md: every catalogued kernel function x who monitors it.

Joins registry/_kernel.yaml against adopted manifests (registry/*.yaml) and drafts
(registry/drafts/*.yaml) on the (tier, category, sub_category) triple.

Usage:
  uv run python scripts/kernel_coverage.py [--write]   # docs/kernel-coverage.md
  uv run python scripts/kernel_coverage.py --embed     # refresh the COVERAGE literal
                                                       # in dashboards/propgf-kernel-health.py
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

from fpm.drafts import split_draft
from fpm.governance.allowlist import host_of
from fpm.kernel import load_kernel
from fpm.manifest import load_manifest

OUT = Path("docs/kernel-coverage.md")


def collect():
    entries = defaultdict(list)  # triple -> [(team, function_id, metric, host, state)]
    for path in sorted(Path("registry").glob("*.yaml")):
        if path.name.startswith("_"):
            continue
        m = load_manifest(path)
        for fn in m.functions:
            host = host_of(fn.source.base_url) if fn.source.kind == "http-json" else "fixture"
            entries[(fn.tier, fn.category, fn.sub_category)].append(
                (m.team, fn.function_id, fn.sla.metric, host or "?", "adopted")
            )
    unmeasured = []  # (team, function, reason)
    for path in sorted(Path("registry/drafts").glob("*.yaml")):
        m, x = split_draft(path)
        for fn in m.functions:
            host = host_of(fn.source.base_url) if fn.source.kind == "http-json" else "fixture"
            entries[(fn.tier, fn.category, fn.sub_category)].append(
                (m.team, fn.function_id, fn.sla.metric, host or "?", "draft")
            )
        for u in x.get("unmeasured") or []:
            unmeasured.append((m.team, u.get("function", "?"), u.get("reason", "")))
    return entries, unmeasured


def render() -> str:
    kernel = load_kernel()
    entries, unmeasured = collect()
    lines = [
        "# Kernel coverage matrix",
        "",
        "Auto-generated by `scripts/kernel_coverage.py` — do not edit by hand.",
        "Every catalogued kernel function (registry/_kernel.yaml) and the metrics that",
        "monitor it, from adopted manifests (registry/) plus any pending drafts",
        "(registry/drafts/). `fixture` sources are placeholders awaiting a real feed.",
        "",
    ]
    covered = live = 0
    cur_tier = None
    for e in kernel.entries:
        triple = (e.tier, e.category, e.sub_category)
        if e.tier != cur_tier:
            cur_tier = e.tier
            lines += [f"## {e.tier.upper()}", ""]
        matches = entries.get(triple, [])
        real = [m for m in matches if m[4] != "" and m[3] != "fixture"]
        mark = "🟢" if real else ("🟡" if matches else "🔴")
        covered += bool(matches)
        live += bool(real)
        lines += [f"### {mark} {e.function}", ""]
        if e.value:
            lines += [f"> {e.value}", ""]
        if matches:
            lines += ["| team | metric | source | state |", "|---|---|---|---|"]
            for team, fid, metric, host, state in matches:
                lines.append(f"| {team} | `{metric}` ({fid}) | {host} | {state} |")
            lines.append("")
        else:
            lines += ["_No monitoring entry yet._", ""]
    n = len(kernel.entries)
    lines[6:6] = [
        f"**{covered}/{n} functions have at least one entry; "
        f"{live}/{n} have at least one live (non-fixture) source.** "
        "🟢 live · 🟡 fixture/placeholder only · 🔴 nothing.",
        "",
    ]
    if unmeasured:
        lines += [
            "## Declared unmeasurable / candidate gaps",
            "",
            "Honest gaps recorded by drafts (`x_draft.unmeasured`):",
            "",
            "| team | aspect | reason |",
            "|---|---|---|",
        ]
        for team, fn_text, reason in unmeasured:
            lines.append(f"| {team} | {fn_text[:70]} | {reason[:110]} |")
        lines.append("")
    return "\n".join(lines)


DASHBOARD = Path("dashboards/propgf-kernel-health.py")
EMBED_START = "    # COVERAGE-EMBED-START (regenerate: uv run python scripts/kernel_coverage.py --embed)"
EMBED_END = "    # COVERAGE-EMBED-END"


def coverage_json() -> dict:
    """The dashboard's embedded coverage payload: 29 functions x monitoring entries."""
    import json as _json

    kernel = load_kernel()
    entries, _ = collect()
    # lineage per (team, function_id): "oso" | "karma" | "external-pr"
    origins: dict[tuple[str, str], str] = {}
    for path in sorted(Path("registry").glob("*.yaml")):
        if path.name.startswith("_"):
            continue
        m = load_manifest(path)
        for fn in m.functions:
            origins[(m.team, fn.function_id)] = fn.origin
    functions = []
    for e in kernel.entries:
        functions.append(
            {
                "tier": e.tier,
                "category": e.category,
                "sub_category": e.sub_category,
                "function": e.function,
                "entries": [
                    {"team": t, "function_id": f, "metric": m, "host": h, "state": s,
                     "origin": origins.get((t, f), "oso")}
                    for t, f, m, h, s in entries.get((e.tier, e.category, e.sub_category), [])
                ],
            }
        )
    team_app_refs = {}
    for path in sorted(Path("registry/drafts").glob("*.yaml")):
        m, x = split_draft(path)
        refs = x.get("app_ref")
        if isinstance(refs, str) and refs.strip():
            team_app_refs[m.team] = [r.strip() for r in refs.split(",") if r.strip()]
        slates = x.get("slates")
        if isinstance(slates, list):
            team_app_refs.setdefault(m.team, [])
            for s in slates:
                if s.get("app_ref"):
                    team_app_refs[m.team].append(s["app_ref"])
    return {"functions": functions, "team_app_refs": team_app_refs}


def embed() -> None:
    import json as _json

    payload = _json.dumps(coverage_json(), indent=None, sort_keys=True)
    text = DASHBOARD.read_text()
    start = text.index(EMBED_START)
    end = text.index(EMBED_END)
    new = (
        text[:start]
        + EMBED_START
        + "\n    COVERAGE = _json.loads(\n        "
        + repr(payload)
        + "\n    )\n"
        + text[end:]
    )
    DASHBOARD.write_text(new)
    print(f"embedded coverage into {DASHBOARD} ({len(payload)} bytes)")


README = Path("README.md")
BADGES_START = "<!-- BADGES-START (regenerate: uv run python scripts/kernel_coverage.py --badges) -->"
BADGES_END = "<!-- BADGES-END -->"


def badges() -> None:
    """Refresh the shields.io count badges in README between the BADGES markers."""
    kernel = load_kernel()
    n_fn = len(kernel.entries)
    teams = [p for p in sorted(Path("registry").glob("*.yaml")) if not p.name.startswith("_")]
    n_metrics = sum(len(load_manifest(p).functions) for p in teams)
    n_cov = sum(1 for f in coverage_json()["functions"] if f["entries"])
    _wf = "https://github.com/filecoin-project/pgf-monitor/actions/workflows/validate.yml"
    block = (
        f"{BADGES_START}\n"
        "<p>\n"
        f'  <img src="https://img.shields.io/badge/kernel_functions-{n_fn}-0D9488" alt="{n_fn} kernel functions">\n'
        f'  <img src="https://img.shields.io/badge/monitored_metrics-{n_metrics}-0D9488" alt="{n_metrics} monitored metrics">\n'
        f'  <img src="https://img.shields.io/badge/teams-{len(teams)}-0D9488" alt="{len(teams)} teams">\n'
        f'  <img src="https://img.shields.io/badge/coverage-{n_cov}%2F{n_fn}-16A34A" alt="{n_cov}/{n_fn} functions covered">\n'
        f'  <a href="{_wf}"><img src="{_wf}/badge.svg" alt="Validate"></a>\n'
        '  <a href="LICENSE"><img src="https://img.shields.io/badge/license-MIT-blue.svg" alt="License: MIT"></a>\n'
        "</p>\n"
        f"{BADGES_END}"
    )
    text = README.read_text()
    start = text.index(BADGES_START)
    end = text.index(BADGES_END) + len(BADGES_END)
    README.write_text(text[:start] + block + text[end:])
    print(f"updated README badges: {n_fn} functions, {n_metrics} metrics, {len(teams)} teams, {n_cov}/{n_fn} covered")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help=f"write {OUT} instead of stdout")
    ap.add_argument("--embed", action="store_true", help="refresh the dashboard COVERAGE literal")
    ap.add_argument("--badges", action="store_true", help="refresh the README count badges")
    args = ap.parse_args(argv)
    if args.embed:
        embed()
        return 0
    if args.badges:
        badges()
        return 0
    md = render()
    if args.write:
        OUT.write_text(md)
        print(f"wrote {OUT} ({len(md.splitlines())} lines)")
    else:
        print(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
